from games.tic_tac_toe import TicTacToe
from games.movement_game_base import MovementGameBase
from games.game2_free_move import FreeMove
from games.game3_tapatan import Tapatan
from games.game4_shisima import Shisima
from games.game5_tsoro import TsoroYematatu
from games.placement_movement_base import PlacementMovementBase
from games.game6_placement_free import ColMaisLivre
from games.game7_achi4 import Achi4
from games.game8_achi3 import Achi3
from games.game9_placement_center import ColMaisCentro
from games.game10_placement_jump import ColMaisSalto
from games.blocking_game_base import BlockingGameBase
from games.game11_mu_torere_v1 import MuTorereV1
from games.game12_mu_torere_v2 import MuTorereV2
from games.game13_mu_torere_v3 import MuTorereV3
from games.amazonas_base import AmazonasBase
from games.game14_amazonas_v1 import AmazonasV1
from games.game15_amazonas_v2 import AmazonasV2
from games.game16_amazonas_v3 import AmazonasV3
from games.game17_amazonas_v4 import AmazonasV4
from games.game18_desafio_tapatan import DesafioTapatan
from games.game19_desafio_cavalo_v1 import DesafioCavaloV1
from games.game20_desafio_cavalo_v2 import DesafioCavaloV2
from games.game21_desafio_cavalo_v3 import DesafioCavaloV3
from games.registry import GAMES, BONUS_GAMES, CATEGORIES, get_game_class
