import { GameMetadata, CategoryMetadata } from './types';

export const GAMES: GameMetadata[] = [
  // ─── ALINHAMENTO: Apenas Colocação ──────────────────────────
  {
    id: 'tictactoe',
    num: 1,
    name: 'Jogo da Velha',
    name_alt: 'Tic-Tac-Toe',
    category: 'Alinhamento',
    subcategory: 'Apenas Colocação',
    origin: 'Tradicional mundial',
    description: 'O clássico! Coloque peças alternadamente e seja o primeiro a alinhar três.',
    available: true,
  },
  // ─── ALINHAMENTO: Apenas Movimentação ───────────────────────
  {
    id: 'free-move',
    num: 2,
    name: 'Movimento Livre',
    name_alt: null,
    category: 'Alinhamento',
    subcategory: 'Apenas Movimentação',
    origin: null,
    description: 'Peças já posicionadas. Qualquer peça pode mover para qualquer posição livre.',
    available: true,
  },
  {
    id: 'tapatan',
    num: 3,
    name: 'Tapatan',
    name_alt: null,
    category: 'Alinhamento',
    subcategory: 'Apenas Movimentação',
    origin: 'Indonésia / Filipinas',
    description: 'Peças movem para posições vizinhas livres pelas linhas do tabuleiro.',
    available: true,
  },
  {
    id: 'shisima',
    num: 4,
    name: 'Shisima',
    name_alt: null,
    category: 'Alinhamento',
    subcategory: 'Apenas Movimentação',
    origin: 'Quênia',
    description: 'Como Tapatan, mas o alinhamento vitorioso deve passar pelo centro.',
    available: true,
  },
  {
    id: 'tsoro-yematatu',
    num: 5,
    name: 'Tsoro Yematatu',
    name_alt: null,
    category: 'Alinhamento',
    subcategory: 'Apenas Movimentação',
    origin: 'Zimbábue',
    description: 'Além de mover para vizinhos, permite saltar sobre peças em linha reta.',
    available: true,
  },
  // ─── ALINHAMENTO: Colocação e Movimentação ──────────────────
  {
    id: 'placement-free-move',
    num: 6,
    name: 'Colocação + Livre',
    name_alt: null,
    category: 'Alinhamento',
    subcategory: 'Colocação e Movimentação',
    origin: null,
    description: 'Fase de colocação seguida de movimentação livre para qualquer posição vazia.',
    available: true,
  },
  {
    id: 'achi',
    num: 7,
    name: 'Achi',
    name_alt: '4 peças',
    category: 'Alinhamento',
    subcategory: 'Colocação e Movimentação',
    origin: 'Gana',
    description: 'Cada jogador tem 4 peças. Fase de colocação, depois movimentação pelas linhas.',
    available: true,
  },
  {
    id: 'achi3',
    num: 8,
    name: 'Achi (3 peças)',
    name_alt: null,
    category: 'Alinhamento',
    subcategory: 'Colocação e Movimentação',
    origin: 'Gana',
    description: 'Versão do Achi com 3 peças por jogador — mais dinâmico e veloz.',
    available: true,
  },
  {
    id: 'placement-center',
    num: 9,
    name: 'Colocação + Centro',
    name_alt: null,
    category: 'Alinhamento',
    subcategory: 'Colocação e Movimentação',
    origin: null,
    description: 'Colocação seguida de movimentação; alinhamento válido deve passar pelo centro.',
    available: true,
  },
  {
    id: 'placement-jump',
    num: 10,
    name: 'Colocação + Salto',
    name_alt: 'Tsoro style',
    category: 'Alinhamento',
    subcategory: 'Colocação e Movimentação',
    origin: 'Zimbábue',
    description: 'Colocação seguida de movimentação com saltos — regras do Tsoro Yematatu.',
    available: true,
  },
  // ─── BLOQUEIO: Mu Torere ────────────────────────────────────
  {
    id: 'mu-torere-1',
    num: 11,
    name: 'Mu Torere (V1)',
    name_alt: null,
    category: 'Bloqueio',
    subcategory: 'Mu Torere',
    origin: 'Nova Zelândia (Maori)',
    description: 'Peças dispostas alternadamente. Mova pelas linhas do tabuleiro. Quem não conseguir mover perde.',
    available: true,
  },
  {
    id: 'mu-torere-2',
    num: 12,
    name: 'Mu Torere (V2)',
    name_alt: null,
    category: 'Bloqueio',
    subcategory: 'Mu Torere',
    origin: 'Nova Zelândia (Maori)',
    description: 'Fase de colocação (4 peças cada), depois movimentação pelas linhas. Quem não conseguir mover perde.',
    available: true,
  },
  {
    id: 'mu-torere-3',
    num: 13,
    name: 'Mu Torere (V3)',
    name_alt: 'Original',
    category: 'Bloqueio',
    subcategory: 'Mu Torere',
    origin: 'Nova Zelândia (Maori)',
    description: 'Posição inicial em L. Regra especial: nas 2 primeiras jogadas de cada jogador, é proibido mover ao centro.',
    available: true,
  },
  // ─── NÃO IMPLEMENTADOS ────────────────
  { id: 'amazonas-1', num: 14, name: 'Amazonas (V1)', name_alt: '1 peça', category: 'Bloqueio', subcategory: 'Amazonas', origin: 'Argentina (adaptado)', description: 'Mova sua peça e lance uma peça de bloqueio. Quem ficar preso perde.', available: true },
  { id: 'amazonas-2', num: 15, name: 'Amazonas (V2)', name_alt: '2 peças', category: 'Bloqueio', subcategory: 'Amazonas', origin: 'Argentina (adaptado)', description: 'Cada jogador com 2 peças pré-posicionadas. Jogo mais complexo.', available: true },
  { id: 'amazonas-3', num: 16, name: 'Amazonas (V3)', name_alt: '1 peça, fora', category: 'Bloqueio', subcategory: 'Amazonas', origin: 'Argentina (adaptado)', description: 'Peça começa fora; o primeiro lance é posicioná-la. Mais estratégia inicial.', available: true },
  { id: 'amazonas-4', num: 17, name: 'Amazonas (V4)', name_alt: '2 peças, fora', category: 'Bloqueio', subcategory: 'Amazonas', origin: 'Argentina (adaptado)', description: 'Duas peças fora do tabuleiro. Fase de colocação + movimentação com bloqueio.', available: true },
  { id: 'desafio-tapatan', num: 18, name: 'Desafio: Troca de Lado', name_alt: 'Tapatan', category: 'Desafio', subcategory: 'Individual', origin: null, description: 'Troque as peças de lado no menor número de movimentos. Movimento Tapatan.', available: true },
  { id: 'desafio-cavalo-1', num: 19, name: 'Desafio: Cavalo (1)', name_alt: '1 peça', category: 'Desafio', subcategory: 'Individual', origin: null, description: 'Troque 1 peça de cada lado usando o movimento do Cavalo do Xadrez.', available: true },
  { id: 'desafio-cavalo-2', num: 20, name: 'Desafio: Cavalo (2)', name_alt: '2 peças', category: 'Desafio', subcategory: 'Individual', origin: null, description: 'Troque 2 peças de cada lado usando o movimento do Cavalo do Xadrez.', available: true },
  { id: 'desafio-cavalo-3', num: 21, name: 'Desafio: Cavalo (3)', name_alt: '3 peças', category: 'Desafio', subcategory: 'Individual', origin: null, description: 'Troque 3 peças de cada lado usando o movimento do Cavalo do Xadrez.', available: true }
];

export const BONUS_GAMES = [
  { id: 'ultimate-ttt', name: 'Ultimate Tic-Tac-Toe', description: 'Nove partidas simultâneas! Sua jogada determina em qual tabuleiro o adversário joga.', available: false },
  { id: 'ultimate-amazonas', name: 'Ultimate Amazonas', description: 'A dinâmica do Ultimate aplicada ao jogo de bloqueio Amazonas.', available: false },
];

export const CATEGORIES: CategoryMetadata[] = [
  { id: 'Alinhamento', icon: '⊞', label: 'Jogos de Alinhamento', subcategories: ['Apenas Colocação', 'Apenas Movimentação', 'Colocação e Movimentação'] },
  { id: 'Bloqueio', icon: '🚧', label: 'Jogos de Bloqueio', subcategories: ['Mu Torere', 'Amazonas'] },
  { id: 'Desafio', icon: '🧩', label: 'Desafios Individuais', subcategories: ['Individual'] }
];
